version: '3'

services:
  webserver:
    build: .
    ports:
      - '8181:80'
    volumes:
      - ../web/htdocs:/var/www/html
      - ../web/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ../conf/php.ini:/etc/php/7.2/apache2/php.ini
